# Generated by Django 3.2.23 on 2024-04-27 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
    ]
